services:
  nb4mna:
    image: nb4mna:0.1.1
    build: .
    env_file: .env
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
#    healthcheck:
#      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8000/healthcheck/"]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#      start_period: 30s
