version: "3.8"

services:
  nb4mna:
    image: nb4mna:0.1.0
    env_file: .env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.nb4mna.loadbalancer.server.port=8000"
        - "traefik.http.routers.nb4mna.tls=true"
        - "traefik.http.routers.nb4mna.rule=Host(`nb4mna.pen.gy`)"
        - "traefik.http.routers.nb4mna.tls.certresolver=letsencrypt"
        - "traefik.http.routers.nb4mna.middlewares=nb4mnasts"
        - "traefik.http.middlewares.nb4mnasts.headers.stsincludesubdomains=false"
        - "traefik.http.middlewares.nb4mnasts.headers.stsseconds=31536000"
        - "traefik.http.middlewares.nb4mnasts.headers.isdevelopment=false"
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
#    healthcheck:
#      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8000/healthcheck/"]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#      start_period: 30s
